source ~/.zsh/colors.zsh
source ~/.zsh/setopt.zsh
source ~/.zsh/history.zsh
source ~/.zsh/exports.zsh
source ~/.zsh/prompt.zsh
source ~/.zsh/completion.zsh
source ~/.zsh/aliases.zsh
source ~/.zsh/bindkeys.zsh

# app specific
source ~/.zsh/pew.zsh
source ~/.zsh/tmuxp.zsh
source ~/.zsh/python.zsh
